### ISSUE TITLE
Tapas-Comic-Downloader doesn't work anymore

### ISSUE THREAD

**Issue by Pan1971** [TilCreator/Tapas-Comic-Downloader#47]
It has worked flawlessly for a long time but now suddenly it won't. The problem occurs both with new comics and old ones that worked before. Maybe it would benefit from an update?

Below is the output from the command prompt from which I started the tool. It looks similar no matter which comic I use it for.

Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 1 (char 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\OneDrive\Downloads\TapasDownloader\tapas-dl.py", line 107, in <module>
    .json()['data']['body'])
     ^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 5 column 1 (char 4)

**Comment by lennyjamin** [comment]
Same issue on windows.

**Comment by PsyckoCoder** [comment]
The same thing happens on Windows 10 ltsc and Ubuntu 22.04; in the python 3.10 virtual environment it seems to work but still gives error.

I hope it will be fixed soon.

**Comment by SpacemannFinn** [comment]
Yeah it's a 403 error I keep getting whenever I try to access python with any script. I think maybe giving the tool my tapas login cookies would help?

**Comment by Ari-Man** [comment]
Same here even when i give it my cookies

**Comment by datagutten** [comment]
The script attempts to get 99999999 episodes, but the site now enforces a limit of 20 per page. The script needs to updated to support pagination.
